name: Continuous Integration

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
                    # @todo run some tests on 'windows-latest'
                    - php: '8.4'
                      operating-system: ubuntu-24.04
                    - php: '8.3'
                      operating-system: ubuntu-24.04
                    - php: '8.2'
                      operating-system: ubuntu-22.04
                    - php: '8.1'
                      operating-system: ubuntu-22.04

        steps:
            - run: echo "Job was automatically triggered by a ${{ github.event_name }} event"
            - run: echo "Job is now running on a ${{ runner.os }} server"
            - run: echo "Branch is ${{ github.ref }} and Repository is ${{ github.repository }}"
            - run: echo "Current directory is ${{ github.workspace }}, current user is $(id -u -n)"

            #- name: Install required packages
            #  run: |
            #    sudo apt-get -y install fonts-dejavu

            # has to be run before setting up the db and webserver, as we store their config files in the codebase
            - name: Check out repository code
              uses: actions/checkout@v3

            - name: Set up the Database
              # @todo we should set up a different version of mysql/mariadb for each matrix combination. Use Docker?
              #       Also, somtimes use a different port number than 3306, to stress the config
              # @see https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#mysql
              # @see https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#mysql
              run: |
                chmod 755 ./tests/setup/setup_db.sh
                ./tests/setup/setup_db.sh

            - name: Stop php-fpm if running
              run: |
                if ps auxwww | fgrep -q php-fpm; then
                    PHPVER=$(php -r 'echo implode(".",array_slice(explode(".",PHP_VERSION),0,2));' 2>/dev/null)
                    sudo service "php${PHPVER}-fpm" stop || sudo pkill php-fpm
                fi

            - name: Set up the required php version
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: bcmath, calendar, curl, ftp, gd, gettext, iconv, mbstring, mysqli, simplexml, sqlite3, xdebug, xml, zip, zlib

            # @todo set up specific php config if needed, eg. display_errors

            - name: Set up the Webserver
              # @todo we should set up either nginx or apache depending on the matrix combination
              run: |
                chmod 755 ./tests/setup/setup_webserver.sh
                ./tests/setup/setup_webserver.sh

            - name: Install dev dependencies
              run: |
                chmod 755 ./tests/setup/run_composer.sh
                ./tests/setup/run_composer.sh

            # Make sure Apache can access the installation in its current dir.
            # We set the installation to be fully writeable to anyone - this is a test install anyway
            # @todo the `/home/runner` path should not be hardcoded. Figure out if we can get if from some GH param
            - name: Fix filesystem permissions
              run: |
                sudo chmod g+rx,o+rx /home/
                sudo chmod -R g+rwX,o+rwX /home/runner/

            - name: Check syntax of php files
              run: |
                chmod 755 ./build/check_syntax.sh
                ./build/check_syntax.sh

            - name: Run the test suite
              run: |
                # smoke-testing
                #curl -L --fail-with-body http://localhost/images/default_logo.jpg
                #echo
                #curl -L --fail-with-body http://localhost/index.php

                ./vendor/bin/phpunit tests/install
                ./vendor/bin/phpunit tests/run

            - name: Failure troubleshooting
              if: ${{ failure() }}
              run: |
                echo '### running processes'
                ps auxwww | grep -E -v '^root .+:[0-9]{2} \[' | grep -v ' grep'

                #echo '### fpm socket(s)'
                #ls -la /run/php/

                #sudo ls -la /var/log/apache2/
                #sudo cat /var/log/apache2/error.log
                echo
                echo '### apache access log'
                sudo cat /var/log/apache2/access.log
